version : 0.7.{build}

environment:
  VSVER: 12.0
  matrix:
    - QTDIR: C:\Qt\5.5\mingw492_32
      CRYPT:
    - QTDIR: C:\Qt\5.5\mingw492_32
      CRYPT: CRYPT
    - QTDIR: C:\Qt\5.5\msvc2013
      CRYPT:
    - QTDIR: C:\Qt\5.5\msvc2013
      CRYPT: CRYPT

configuration:
  - debug
  - release

install:
  - '%QTDIR%\bin\qtenv2.bat'
  - set ARCH=x86
  - if %QTDIR:msvc=%==%QTDIR% set make=mingw32-make.exe
  - if not %QTDIR:msvc=%==%QTDIR% call "%ProgramFiles(x86)%\Microsoft Visual Studio %VSVER%\VC\vcvarsall.bat" %ARCH%
  - if not %QTDIR:msvc=%==%QTDIR% set make=nmake.exe

before_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - qmake CONFIG+=%CONFIGURATION% CONFIG+=%CRYPT% %APPVEYOR_BUILD_FOLDER%\EffortLog.pro

build_script:
  - '%make%'

after_build:
  - if %QTDIR:msvc=%==%QTDIR% ..\..\tools\windows_deploy.bat
  - if %CRYPT%==CRYPT ..\..\tools\windows_deploy_encrypted.bat

artifacts:
  - path: effort-log*.exe
    name: effort-log

deploy:
  - provider: GitHub
    artifact: effort-log
    draft: true
    prerelease: false
    auth_token:
      secure: Fgg1YNvCvhz8eHvfWofM9Z4kumoEpzvhQ53yEuW4Iw3KJbDZ8HxacFyq7pV6Pc32
    on:
      branch: master
