version : 0.7.{build}

environment:
  VSVER: 12.0
  matrix:
    - QTDIR: C:\Qt\5.6\mingw492_32
      CRYPT: false
    - QTDIR: C:\Qt\5.6\mingw492_32
      CRYPT: true

configuration:
  - debug
  - release

install:
  - '%QTDIR%\bin\qtenv2.bat'
  - set ARCH=x86

before_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - if %CRYPT%==false (qmake CONFIG+=%CONFIGURATION% %APPVEYOR_BUILD_FOLDER%\EffortLog.pro)
  - if %CRYPT%==true (qmake CONFIG+=%CONFIGURATION% CONFIG+=crypt %APPVEYOR_BUILD_FOLDER%\EffortLog.pro)

build_script:
  - mingw32-make.exe

after_build:
  - ps: |
      if($env:CONFIGURATION -eq "release") {
        if($env:CRYPT  -eq "CRYPT") {
          C:\projects\effort-log\tools\windows_deploy_encrypted.bat
        } else {
          C:\projects\effort-log\tools\windows_deploy.bat
        }
      }

artifacts:
  - path: effort-log_v*.zip
    name: effort-log

deploy:
  - provider: GitHub
    release: $(APPVEYOR_REPO_TAG_NAME)
    description: ''
    artifact: effort-log
    draft: false
    prerelease: false
    auth_token:
      secure: Fgg1YNvCvhz8eHvfWofM9Z4kumoEpzvhQ53yEuW4Iw3KJbDZ8HxacFyq7pV6Pc32
    on:
      appveyor_repo_tag: true
