version : 0.7.{build}

environment:
  VSVER: 12.0
  matrix:
    - QTDIR: C:\Qt\5.5\mingw492_32
      CRYPT:  
    - QTDIR: C:\Qt\5.5\mingw492_32
      CRYPT: CRYPT
    - QTDIR: C:\Qt\5.5\msvc2013
      CRYPT:
    - QTDIR: C:\Qt\5.5\msvc2013
      CRYPT: Crypt

configuration:
  - debug
  - release

install:
  - '%QTDIR%\bin\qtenv2.bat'
  - set ARCH=x86
  - if %QTDIR:msvc=%==%QTDIR% set make=mingw32-make.exe
  - if not %QTDIR:msvc=%==%QTDIR% call "%ProgramFiles(x86)%\Microsoft Visual Studio %VSVER%\VC\vcvarsall.bat" %ARCH%
  - if not %QTDIR:msvc=%==%QTDIR% set make=nmake.exe

before_build:
  - qmake CONFIG+=%CONFIGURATION% CONFIG+=%CRYPT% .

build_script:
  - '%make%'
