version : 0.9.{build}

environment:
  matrix:
    - QTDIR: C:\Qt\5.9.7\mingw53_32
      CRYPT: false
      DEPLOY: true
      64BIT: false
    - QTDIR: C:\Qt\5.9.7\mingw53_32
      CRYPT: true
      DEPLOY: true
      64BIT: false
    - QTDIR: C:\Qt\5.12.1\mingw73_64
      CRYPT: false
      DEPLOY: true
      64BIT: true
    - QTDIR: C:\Qt\5.12.1\mingw73_64
      CRYPT: true
      DEPLOY: true
      64BIT: true

configuration:
  - debug
  - release

install:
  - '%QTDIR%\bin\qtenv2.bat'
  - set ARCH=x86

before_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - if %CRYPT%==false (qmake CONFIG+=%CONFIGURATION% %APPVEYOR_BUILD_FOLDER%\EffortLog.pro)
  - if %CRYPT%==true (qmake CONFIG+=%CONFIGURATION% CONFIG+=crypt %APPVEYOR_BUILD_FOLDER%\EffortLog.pro)

build_script:
  - mingw32-make.exe

after_build:
  - ps: |
      if($env:CONFIGURATION -eq "release") {
        if($env:DEPLOY -eq "true") {
          if($env:64BIT -eq "true") {
            if($env:CRYPT -eq "true") {
              C:\projects\effort-log\tools\windows_deploy_64_encrypted.bat
            } else {
              C:\projects\effort-log\tools\windows_deploy_64.bat
            }
          } else {
            if($env:CRYPT -eq "true") {
              C:\projects\effort-log\tools\windows_deploy_32_encrypted.bat
            } else {
              C:\projects\effort-log\tools\windows_deploy_32.bat
            }
          }
        }
      }

artifacts:
  - path: effort-log*.zip
    name: effort-log

deploy:
  - provider: GitHub
    release: $(APPVEYOR_REPO_TAG_NAME)
    description: ''
    artifact: effort-log
    draft: false
    prerelease: false
    auth_token:
      secure: Fgg1YNvCvhz8eHvfWofM9Z4kumoEpzvhQ53yEuW4Iw3KJbDZ8HxacFyq7pV6Pc32
    on:
      appveyor_repo_tag: true
