language: cpp

sudo: required

dist: trusty

cache: ccache

os:
  - linux
  - osx

osx_image: xcode8.3

compiler:
  - clang
  - gcc

env:
  - QT_BASE=58 QT_LONG=58  CONFIG=debug
  - QT_BASE=58 QT_LONG=58  CONFIG=release DEPLOY=true
  - QT_BASE=58 QT_LONG=58  CONFIG=debug CRYPT=crypt
  - QT_BASE=58 QT_LONG=58  CONFIG=release CRYPT=crypt DEPLOY=true

matrix:
  exclude:
    - os: osx
      compiler: gcc

before_install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then sudo add-apt-repository -y ppa:beineri/opt-qt${QT_LONG}-trusty; fi
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then sudo apt-get update -qq; fi
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then sudo apt-get install -y -qq qt${QT_BASE}base qt${QT_BASE}script qt${QT_BASE}tools; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ];   then brew update; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ];   then brew install ccache; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ];   then brew install qt; fi

before_script:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then source /opt/qt${QT_BASE}/bin/qt${QT_BASE}-env.sh; fi
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then export QT_DIR=/opt/qt${QT_BASE}; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ];   then export PATH=/usr/local/opt/ccache/libexec:${PATH}; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ];   then export QT_DIR=/usr/local/opt/qt5/; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ];   then export PATH=/usr/local/opt/qt5/bin:${PATH}; fi
  - which qmake
  - qmake CONFIG+=$CONFIG CONFIG+=$CRYPT

script:
  - make -j2
  - ccache --show-stats

before_deploy:
  - echo "Deployment for tag $TRAVIS_TAG $CRYPT"
  - ${TRAVIS_BUILD_DIR}/tools/mac_osx_deploy.sh $TRAVIS_TAG $CRYPT
  - export DMG_FILE=$(ls $TRAVIS_BUILD_DIR/build/release/*.dmg)
  - echo $(ls $TRAVIS_BUILD_DIR/build/release/)

deploy:
  provider: releases
  api_key:
    secure: LaEzMGIx0sjcO33/NwJOrAXMI9CWZD7JqVZHZNLj76Frwnj6haqMPt1QnAblg1wg+S37AXtDxghT/mt0fJHUgySR9Zl04/5VWEkA87qNr9FHr5VjFkrc5y9++1PSUmhA4N/r7vOquGShcxk18wdAyKpXZY2FBHws8aCAwyjacvVCJM6vACPXAOTU3/4R4GpiXjAyQmhMxLhMWJ0mngB3v/al/jrXsExVsfnB1mr0pN0rFcphHZP8MX8X1og72b3XIO0sUEBSE/j5Gd9BMb5iS4zsCgE6QKkcUxNc8eSBdhA7oeNJQ51UcW12NueE5+u4RdpLkMZWxIq/jofLef6ex/KBLEyM8bW6/Djktky9Bte7TGiVvKTgRwicYCeAI4rTJPdvLV2K+tx8i+0Cyzhsp2+4yze6A6+wGQ8kJUVHuKT6hOGxRvN5hy0MHfP24cVDNzb+lN3/IkCerwhyoz2IXEUB9CxoQkuLeQ/ysLyunjB8oWMqDsbbgO2E/a6SH8TwF1MM6CqA96bcCuK084X5vGnTXXAZewPW7te0WMch8yv+qjYvZ+dJQZvWgHJG5V9ZpS02EI6rHNcdm7+Vp4dCXJsXV1Vo2uR9sr1SFW09imMsWhh2933PkCI8vNTYt6pwk9QyiN/w51jMQQ0fBVq75QslmFrDWrvt41ViTc104DA=
  file: "${DMG_FILE}"
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    condition: '"$DEPLOY" == "true" && "$TRAVIS_OS_NAME" == "osx"'
