language: cpp

sudo: required

dist: trusty

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

env:
  - QT_BASE=56 QT_LONG=562 BREW_QT_VER_SHA=fdfc724dd532345f5c6cdf47dc43e99654e6a5fd CONFIG=debug
  - QT_BASE=56 QT_LONG=562 BREW_QT_VER_SHA=fdfc724dd532345f5c6cdf47dc43e99654e6a5fd CONFIG=release DEPLOY=true
  - QT_BASE=56 QT_LONG=562 BREW_QT_VER_SHA=fdfc724dd532345f5c6cdf47dc43e99654e6a5fd CONFIG=debug CRYPT=crypt
  - QT_BASE=56 QT_LONG=562 BREW_QT_VER_SHA=fdfc724dd532345f5c6cdf47dc43e99654e6a5fd CONFIG=release CRYPT=crypt DEPLOY=true
  - QT_BASE=57 QT_LONG=571 BREW_QT_VER_SHA=805b2e0b0201b2560235eb3ee5c724d241ba42d5 CONFIG=debug
  - QT_BASE=57 QT_LONG=571 BREW_QT_VER_SHA=805b2e0b0201b2560235eb3ee5c724d241ba42d5 CONFIG=release
  - QT_BASE=57 QT_LONG=571 BREW_QT_VER_SHA=805b2e0b0201b2560235eb3ee5c724d241ba42d5 CONFIG=debug CRYPT=crypt
  - QT_BASE=57 QT_LONG=571 BREW_QT_VER_SHA=805b2e0b0201b2560235eb3ee5c724d241ba42d5 CONFIG=release CRYPT=crypt
  - QT_BASE=58 QT_LONG=58  BREW_QT_VER_SHA=e8d5c92686cb4b9f3462dfa946c1f48c74b867f9 CONFIG=debug
  - QT_BASE=58 QT_LONG=58  BREW_QT_VER_SHA=e8d5c92686cb4b9f3462dfa946c1f48c74b867f9 CONFIG=release
  - QT_BASE=58 QT_LONG=58  BREW_QT_VER_SHA=e8d5c92686cb4b9f3462dfa946c1f48c74b867f9 CONFIG=debug CRYPT=crypt
  - QT_BASE=58 QT_LONG=58  BREW_QT_VER_SHA=e8d5c92686cb4b9f3462dfa946c1f48c74b867f9 CONFIG=release CRYPT=crypt

matrix:
  exclude:
    - os: osx
      compiler: gcc

before_install:
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository --yes ppa:beineri/opt-qt${QT_LONG}-trusty
  && sudo apt-get update -qq
  && sudo apt-get install -y -qq qt${QT_BASE}base qt${QT_BASE}script qt${QT_BASE}tools
  && source /opt/qt${QT_BASE}/bin/qt${QT_BASE}-env.sh; fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update
  && curl -O https://raw.githubusercontent.com/Homebrew/homebrew-core/${BREW_QT_VER_SHA}/Formula/qt5.rb
  && brew install qt5.rb'
  && brew link --force qt5'
  && PATH="/usr/local/opt/qt5/bin:$PATH"; fi

before_script:
- qmake CONFIG+=$CONFIG CONFIG+=$CRYPT

script:
- make

before_deploy:
  - if [ "$DEPLOY" = "true" ]; then echo "Deployment for tag $TRAVIS_TAG $CRYPT" && ${TRAVIS_BUILD_DIR}/tools/mac_osx_deploy.sh $TRAVIS_TAG $CRYPT; fi
  - export DMG_FILE=$(ls $TRAVIS_BUILD_DIR/build/release/*.dmg)
  - echo $(ls $TRAVIS_BUILD_DIR/build/release/)

deploy:
  provider: releases
  api_key:
    secure: LaEzMGIx0sjcO33/NwJOrAXMI9CWZD7JqVZHZNLj76Frwnj6haqMPt1QnAblg1wg+S37AXtDxghT/mt0fJHUgySR9Zl04/5VWEkA87qNr9FHr5VjFkrc5y9++1PSUmhA4N/r7vOquGShcxk18wdAyKpXZY2FBHws8aCAwyjacvVCJM6vACPXAOTU3/4R4GpiXjAyQmhMxLhMWJ0mngB3v/al/jrXsExVsfnB1mr0pN0rFcphHZP8MX8X1og72b3XIO0sUEBSE/j5Gd9BMb5iS4zsCgE6QKkcUxNc8eSBdhA7oeNJQ51UcW12NueE5+u4RdpLkMZWxIq/jofLef6ex/KBLEyM8bW6/Djktky9Bte7TGiVvKTgRwicYCeAI4rTJPdvLV2K+tx8i+0Cyzhsp2+4yze6A6+wGQ8kJUVHuKT6hOGxRvN5hy0MHfP24cVDNzb+lN3/IkCerwhyoz2IXEUB9CxoQkuLeQ/ysLyunjB8oWMqDsbbgO2E/a6SH8TwF1MM6CqA96bcCuK084X5vGnTXXAZewPW7te0WMch8yv+qjYvZ+dJQZvWgHJG5V9ZpS02EI6rHNcdm7+Vp4dCXJsXV1Vo2uR9sr1SFW09imMsWhh2933PkCI8vNTYt6pwk9QyiN/w51jMQQ0fBVq75QslmFrDWrvt41ViTc104DA=
  file: "${DMG_FILE}"
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    condition: "$DEPLOY = true"
