language: cpp

services:
  - docker

matrix:
  include:
    - os: linux
      env: OS=ubuntu OS_VERSION=16.04
    - os: linux
      env: OS=ubuntu OS_VERSION=18.04
    - os: linux
      env: OS=ubuntu OS_VERSION=19.04
    - os: linux
      env: OS=debian OS_VERSION=stable
    - os: linux
      env: OS=debian OS_VERSION=testing
    - os: linux
      env: OS=fedora OS_VERSION=29
    - os: linux
      env: OS=fedora OS_VERSION=30
    - os: linux
      env: OS=fedora OS_VERSION=31
    - os: linux
      env: OS=opensuse/leap OS_VERSION=42.3
    - os: linux
      env: OS=opensuse/leap OS_VERSION=15.0
    - os: linux
      env: OS=opensuse/leap OS_VERSION=15.1
    - os: linux
      env: OS=opensuse/tumbleweed OS_VERSION=latest
    - os: linux
      env: OS=archlinux/base OS_VERSION=latest
    - os: osx
      compiler: clang
      env: MACOSX_DEPLOYMENT_TARGET=10.12 CONFIG=debug
    - os: osx
      compiler: clang
      env: MACOSX_DEPLOYMENT_TARGET=10.12 CONFIG=release DEPLOY=true
    - os: osx
      compiler: clang
      env: MACOSX_DEPLOYMENT_TARGET=10.12 CONFIG=debug CRYPT=crypt
    - os: osx
      compiler: clang
      env: MACOSX_DEPLOYMENT_TARGET=10.12 CONFIG=release CRYPT=crypt DEPLOY=true

before_install:
  - if [ "${TRAVIS_OS_NAME}" = "osx" ];   then brew install qt; fi

before_script:
  - if [ "${TRAVIS_OS_NAME}" = "osx" ];   then export QT_DIR=/usr/local/opt/qt5/; export PATH=/usr/local/opt/qt5/bin:${PATH}; qmake CONFIG+=$CONFIG CONFIG+=$CRYPT; fi

script:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then docker run --rm -v $(pwd):/effort-log $OS:$OS_VERSION bash /effort-log/tools/linux_build.sh $OS; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ];   then make -j2; fi

before_deploy:
  - echo "Deployment for tag $TRAVIS_TAG $CRYPT"
  - bash ${TRAVIS_BUILD_DIR}/tools/macos_deploy.sh $TRAVIS_TAG $CRYPT
  - export DMG_FILE=$(ls $TRAVIS_BUILD_DIR/build/release/*.dmg)
  - echo $(ls $TRAVIS_BUILD_DIR/build/release/)

deploy:
  provider: releases
  api_key:
    secure: LaEzMGIx0sjcO33/NwJOrAXMI9CWZD7JqVZHZNLj76Frwnj6haqMPt1QnAblg1wg+S37AXtDxghT/mt0fJHUgySR9Zl04/5VWEkA87qNr9FHr5VjFkrc5y9++1PSUmhA4N/r7vOquGShcxk18wdAyKpXZY2FBHws8aCAwyjacvVCJM6vACPXAOTU3/4R4GpiXjAyQmhMxLhMWJ0mngB3v/al/jrXsExVsfnB1mr0pN0rFcphHZP8MX8X1og72b3XIO0sUEBSE/j5Gd9BMb5iS4zsCgE6QKkcUxNc8eSBdhA7oeNJQ51UcW12NueE5+u4RdpLkMZWxIq/jofLef6ex/KBLEyM8bW6/Djktky9Bte7TGiVvKTgRwicYCeAI4rTJPdvLV2K+tx8i+0Cyzhsp2+4yze6A6+wGQ8kJUVHuKT6hOGxRvN5hy0MHfP24cVDNzb+lN3/IkCerwhyoz2IXEUB9CxoQkuLeQ/ysLyunjB8oWMqDsbbgO2E/a6SH8TwF1MM6CqA96bcCuK084X5vGnTXXAZewPW7te0WMch8yv+qjYvZ+dJQZvWgHJG5V9ZpS02EI6rHNcdm7+Vp4dCXJsXV1Vo2uR9sr1SFW09imMsWhh2933PkCI8vNTYt6pwk9QyiN/w51jMQQ0fBVq75QslmFrDWrvt41ViTc104DA=
  file: "${DMG_FILE}"
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    condition: '"$DEPLOY" == "true" && "$TRAVIS_OS_NAME" == "osx"'
