language: cpp

sudo: required

dist: trusty

env:
  global:
    - QT_BASE=56 QT_LONG=56

matrix:
  fast_finish: true
  include:
    - os: linux
      compiler: gcc
      env: COMPILER=gcc CONFIG=debug
    - os: linux
      compiler: gcc
      env: COMPILER=gcc CONFIG=release
    - os: linux
      compiler: gcc
      env: COMPILER=gcc CONFIG=debug CRYPT=crypt
    - os: linux
      compiler: gcc
      env: COMPILER=gcc CONFIG=release CRYPT=crypt
    - os: linux
      compiler: clang
      env: COMPILER=clang CONFIG=debug
    - os: linux
      compiler: clang
      env: COMPILER=clang CONFIG=release
    - os: linux
      compiler: clang
      env: COMPILER=clang CONFIG=debug CRYPT=crypt
    - os: linux
      compiler: clang
      env: COMPILER=clang CONFIG=release CRYPT=crypt
    - os: osx
      compiler: gcc
      env: COMPILER=gcc CONFIG=debug
    - os: osx
      compiler: gcc
      env: COMPILER=gcc CONFIG=release
    - os: osx
      compiler: gcc
      env: COMPILER=gcc CONFIG=debug CRYPT=crypt
    - os: osx
      compiler: gcc
      env: COMPILER=gcc CONFIG=release CRYPT=crypt
    - os: osx
      compiler: clang
      env: COMPILER=clang CONFIG=debug
    - os: osx
      compiler: clang
      env: COMPILER=clang CONFIG=release DEPLOY=true
    - os: osx
      compiler: clang
      env: COMPILER=clang CONFIG=debug CRYPT=crypt
    - os: osx
      compiler: clang
      env: COMPILER=clang CONFIG=release CRYPT=crypt DEPLOY=true

before_install:
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository --yes ppa:beineri/opt-qt${QT_LONG}-trusty
  && sudo apt-get update -qq
  && sudo apt-get install -y -qq qt${QT_BASE}base qt${QT_BASE}script qt${QT_BASE}tools
  && source /opt/qt${QT_BASE}/bin/qt${QT_BASE}-env.sh; fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; brew install qt5; PATH="/usr/local/opt/qt5/bin:$PATH"; fi

before_script:
- qmake CONFIG+=$CONFIG CONFIG+=$CRYPT

script:
- make

before_deploy:
  - if [ "$DEPLOY" = "true" ]; then echo "Deployment for tag $TRAVIS_TAG $CRYPT" && ${TRAVIS_BUILD_DIR}/tools/mac_osx_deploy.sh $TRAVIS_TAG $CRYPT; fi
  - export DMG_FILE=$(ls $TRAVIS_BUILD_DIR/build/release/*.dmg)
  - echo $(ls $TRAVIS_BUILD_DIR/build/release/)

deploy:
  provider: releases
  api_key:
    secure: LaEzMGIx0sjcO33/NwJOrAXMI9CWZD7JqVZHZNLj76Frwnj6haqMPt1QnAblg1wg+S37AXtDxghT/mt0fJHUgySR9Zl04/5VWEkA87qNr9FHr5VjFkrc5y9++1PSUmhA4N/r7vOquGShcxk18wdAyKpXZY2FBHws8aCAwyjacvVCJM6vACPXAOTU3/4R4GpiXjAyQmhMxLhMWJ0mngB3v/al/jrXsExVsfnB1mr0pN0rFcphHZP8MX8X1og72b3XIO0sUEBSE/j5Gd9BMb5iS4zsCgE6QKkcUxNc8eSBdhA7oeNJQ51UcW12NueE5+u4RdpLkMZWxIq/jofLef6ex/KBLEyM8bW6/Djktky9Bte7TGiVvKTgRwicYCeAI4rTJPdvLV2K+tx8i+0Cyzhsp2+4yze6A6+wGQ8kJUVHuKT6hOGxRvN5hy0MHfP24cVDNzb+lN3/IkCerwhyoz2IXEUB9CxoQkuLeQ/ysLyunjB8oWMqDsbbgO2E/a6SH8TwF1MM6CqA96bcCuK084X5vGnTXXAZewPW7te0WMch8yv+qjYvZ+dJQZvWgHJG5V9ZpS02EI6rHNcdm7+Vp4dCXJsXV1Vo2uR9sr1SFW09imMsWhh2933PkCI8vNTYt6pwk9QyiN/w51jMQQ0fBVq75QslmFrDWrvt41ViTc104DA=
  file: "${DMG_FILE}"
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    condition: "$DEPLOY = true"
