name: build

on: push

jobs:
  build-linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: jurplel/install-qt-action@v2
        with:
          version: 5.15.2
      - uses: actions/checkout@v2
      - run: tools/linux_build.sh ubuntu
      - name: Build
        run: |
          qmake -config release EffortLog.pro
          make
          make clean
      - name: Build encrypted
        run: |
          qmake -config release -config crypt EffortLog.pro
          make
          make clean

  build-macos:
    name: macOS
    runs-on: macos-latest
    steps:
      - uses: jurplel/install-qt-action@v2
        with:
          version: 5.15.2
      - name: Build
        run: |
          qmake -config release EffortLog.pro
          make
          macdeployqt EffortLog.app -always-overwrite -verbose=3 -appstore-compliant -dmg
          mv EffortLog.dmg EffortLog_"${GITHUB_REF}"_osx.dmg
          otool -L EffortLog.app/Contents/MacOS/EffortLog
          make clean
      - name: Build encrypted
        run: |
          qmake -config release -config crypt EffortLog.pro
          make
          macdeployqt EffortLog.app -always-overwrite -verbose=3 -appstore-compliant -dmg
          mv EffortLog.dmg EffortLog_"${GITHUB_REF}"_osx_encrypted.dmg
          otool -L EffortLog.app/Contents/MacOS/EffortLog
          make clean
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: EffortLog_*.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: jurplel/install-qt-action@v2
        with:
          version: 5.15.2
          arch: win64_mingw81
      - uses: actions/checkout@v2
      - name: Build
        shell: cmd
        run: |
          call "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          qmake CONFIG+=release EffortLog.pro
          make
          mkdir bin
          move release\effort-log.exe bin
          7z a effort-log_"${GITHUB_REF}"_win64.zip bin\*
      - name: Build encrypted
        shell: cmd
        run: |
          call "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          qmake CONFIG+=release CONFIG+=crypt EffortLog.pro
          make
          mkdir bin
          move release\effort-log.exe bin
          copy C:\OpenSSL-Win62\libeay64.dll build\release\dist\libeay64.dll
          copy C:\OpenSSL-Win62\libssl64.dll build\release\dist\libssl64.dll
          copy C:\OpenSSL-Win62\ssleay64.dll build\release\dist\ssleay64.dll
          7z a effort-log_"${GITHUB_REF}"_win64.zip bin\*
